# Lab Assignment 2
## With this assignment you will get to know more about gradient descent optimization and writing your own functions with forward and backward (i.e., gradient) passes
## You need to complete all the tasks in this notebook in the lab and show you work to the TA. Edit only those portions in the cells where it asks you to do so!

In [0]:
import torch
from torch.autograd import Variable
from torch.autograd import Function
import torch.nn.functional as F
import numpy as np

## Huber loss function
https://en.wikipedia.org/wiki/Huber_loss

In [0]:
# A loss function measures distance between a predicted and a target tensor
# An implementation of Huber loss function is given below
# We will make use of this loss function in gradient descent optimization
def Huber_Loss(input,delta):
  m = (torch.abs(input)<=delta).detach().float()
  output = torch.sum(0.5*m*input**2 + delta*(1.0-m)*(torch.abs(input)-0.5*delta))
  return output

# Test Huber loss with a couple of different examples

In [3]:
a = torch.tensor([[0.3, 2.0, -3.1],[0.5, 9.2, 0.1]])
print(a.numpy())
ha = Huber_Loss(a,1.0)
print(ha.numpy())

b = torch.tensor([0.3, 2.0])
print(b.numpy())
hb = Huber_Loss(b,1.0)
print(hb.numpy())

[[ 0.3  2.  -3.1]
 [ 0.5  9.2  0.1]]
12.974999
[0.3 2. ]
1.545


# Gradient descent code
## Study the following generic gradient descent optimization code.
## Huber loss f measures the distance between a probability vector `z` and target 1-hot vector `target`.
## When `f.backward` is called, PyTorch first computes $\nabla_z f$ (gradient of `f` with respect to `z`), then by chain rule it computes $\nabla_{var} f = J^{z}_{var} \nabla_z f$, where $J^{z}_{var}$ is the Jacobian of `z` with respect to `var`.
## Next, `optimizer.step()` call adjusts the variable `var` in the opposite direction of $\nabla_{var} f.$

In [0]:
def gradient_descent(var,optimizer,softmax,loss,target,nIter,nPrint):
  for i in range(nIter):
    z = softmax(var)
    f = loss(z-target,1.0)
    optimizer.zero_grad()
    f.backward()
    optimizer.step()
    if i%nPrint==0:
      with np.printoptions(precision=3, suppress=True):
        print("Iteration:",i,"Variable:", z.detach().numpy(),"Loss: %0.6f" % f.item())


# Gradient descent with Huber Loss
## The following cell shows how `gradient_descent` function can be used.
## The cell first creates a target 1-hot vector `y`, where only the 3rd place is on.
## It also creates a variable `x` with random initialization and an optimizer.
## Learning rate and momentum has been set to 0.1 and 0.9, respectively.
## Then it calls `gradient_descent` function.

In [5]:
y = torch.zeros(10)
y[2] = 1.0
print("Target 1-hot vector:",y.numpy())
x = Variable(torch.randn(y.shape),requires_grad=True)

optimizer = torch.optim.SGD([x], lr=1e-1, momentum=0.9) # create an optimizer that will do gradient descent optimization

gradient_descent(x,optimizer,F.softmax,Huber_Loss,y,1000,100)


Target 1-hot vector: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Iteration: 0 Variable: [0.177 0.136 0.043 0.055 0.148 0.11  0.042 0.117 0.141 0.029] Loss: 0.519876
Iteration: 100 Variable: [0.008 0.008 0.942 0.005 0.008 0.007 0.004 0.007 0.008 0.003] Loss: 0.001857
Iteration: 200 Variable: [0.006 0.006 0.957 0.004 0.006 0.005 0.003 0.005 0.006 0.002] Loss: 0.001020
Iteration: 300 Variable: [0.005 0.005 0.964 0.003 0.005 0.004 0.003 0.005 0.005 0.002] Loss: 0.000710
Iteration: 400 Variable: [0.004 0.004 0.969 0.003 0.004 0.004 0.002 0.004 0.004 0.002] Loss: 0.000544


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  This is separate from the ipykernel package so we can avoid doing imports until


Iteration: 500 Variable: [0.004 0.004 0.972 0.003 0.004 0.004 0.002 0.004 0.004 0.002] Loss: 0.000441
Iteration: 600 Variable: [0.003 0.003 0.974 0.002 0.003 0.003 0.002 0.003 0.003 0.001] Loss: 0.000371
Iteration: 700 Variable: [0.003 0.003 0.976 0.002 0.003 0.003 0.002 0.003 0.003 0.001] Loss: 0.000319
Iteration: 800 Variable: [0.003 0.003 0.978 0.002 0.003 0.003 0.002 0.003 0.003 0.001] Loss: 0.000281
Iteration: 900 Variable: [0.003 0.003 0.979 0.002 0.003 0.003 0.002 0.003 0.003 0.001] Loss: 0.000250


# <font color='red'>20% Weight:</font> In this markdown cell, using [math mode](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html), write gradient of Huber loss function: $output = \sum_i 0.5 m_i (input)^{2}_{i} + \delta (1-m_i)(|input_i|-0.5 \delta)$ with respect to $input.$ Treat $m_i$ to be independent of $input_i,$ because we replaced *if* control statement with $m_i.$
## Your solution <font color='red'>20% (complete formula)</font>: $\frac{\partial (output)}{\partial (input)_i} = m_i (input)_{i} + (1-m_i) \delta \frac{input_{i}}{|input_i|}$ 

# <font color='red'>20% Weight:</font> Define your own (correct!) rule of differentiation for Huber loss function
## Edit indicated line in the cell below. Use the following formula. Do not use for/while/any loop in your solution.
## For this function,  chain rule (Jacobian-vector product) takes the following form: $\frac{\partial (cost)}{\partial (input)_i} = \frac{\partial (output)}{\partial (input)_i} \frac{\partial (cost)}{\partial (output)}.$
# In the `backward` method below, $\frac{\partial (cost)}{\partial (output)}$ is denoted by `output_grad` and the $i^{th}$ component of `input_grad` is symbolized by $\frac{\partial (cost)}{\partial (input)_i}.$

In [0]:
# Inherit from torch.autograd.Function
class My_Huber_Loss(Function):

    # Note that both forward and backward are @staticmethods
    @staticmethod
    def forward(ctx, input, delta):
        m = (torch.abs(input)<=delta).float()
        ctx.save_for_backward(input,torch.tensor(m),torch.tensor(delta))
        output = torch.sum(0.5*m*input**2 + delta*(1.0-m)*(torch.abs(input)-0.5*delta))
        return output

    @staticmethod
    def backward(ctx, output_grad):
        # retrieve saved tensors and use them in derivative calculation
        input, m, delta = ctx.saved_tensors

        # Return Jacobian-vector product (chain rule)
        # For Huber loss function the Jacobian happens to be a diagonal matrix
        # Also, note that output_grad is a scalar, because forward function returns a scalar value
        input_grad = (m * input + (1-m) * delta * input / torch.abs(input)) * output_grad # complete this line, do not use for loop
        # must return two gradients becuase forward function takes in two arguments
        return input_grad, None

#Gradient Descent on Your Own Huber Loss
## You should get almost identical results as before if your rule of differentation is correct!

In [7]:
y = torch.zeros(10)
y[2] = 1.0
print("Target:",y.numpy())
x = Variable(torch.randn(y.shape),requires_grad=True)

optimizer = torch.optim.SGD([x], lr=1e-1, momentum=0.9) # create an optimizer that will do gradient descent optimization

gradient_descent(x,optimizer,F.softmax,My_Huber_Loss.apply,y,1000,100)


Target: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Iteration: 0 Variable: [0.119 0.073 0.084 0.157 0.091 0.097 0.019 0.02  0.058 0.281] Loss: 0.491799
Iteration: 100 Variable: [0.008 0.006 0.947 0.008 0.007 0.007 0.002 0.002 0.005 0.008] Loss: 0.001579
Iteration: 200 Variable: [0.006 0.005 0.959 0.006 0.005 0.005 0.002 0.002 0.004 0.006] Loss: 0.000936
Iteration: 300 Variable: [0.005 0.004 0.966 0.005 0.004 0.005 0.001 0.001 0.003 0.005] Loss: 0.000667


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys


Iteration: 400 Variable: [0.004 0.004 0.97  0.005 0.004 0.004 0.001 0.001 0.003 0.004] Loss: 0.000517
Iteration: 500 Variable: [0.004 0.003 0.973 0.004 0.004 0.004 0.001 0.001 0.003 0.004] Loss: 0.000423
Iteration: 600 Variable: [0.004 0.003 0.975 0.004 0.003 0.003 0.001 0.001 0.003 0.004] Loss: 0.000357
Iteration: 700 Variable: [0.003 0.003 0.977 0.003 0.003 0.003 0.001 0.001 0.002 0.003] Loss: 0.000309
Iteration: 800 Variable: [0.003 0.003 0.978 0.003 0.003 0.003 0.001 0.001 0.002 0.003] Loss: 0.000272
Iteration: 900 Variable: [0.003 0.002 0.979 0.003 0.003 0.003 0.001 0.001 0.002 0.003] Loss: 0.000244


# <font color='red'>30% Weight:</font> In this markdown cell, using math mode, write Jacobian of softmax function: $(output)_i = \frac{exp((input)_i)}{ \sum_k exp((input)_k)}.$
## Your solution (<font color='red'>show your derivation to TA</font>): On Paper 
\begin{equation*}
    \frac{\partial (output)_j}{\partial (input)_i} = \begin{cases}
               (output)_j -(output)_j (output)_i,               & i = j,\\
               -(output)_j (output)_i, & \text{otherwise.}
           \end{cases}
\end{equation*}

# <font color='red'>30% Weight:</font> Your own softmax with forward and backward functions
## Edit indicated line in the cell below. Use the following formula. Do not use for/while/any loop in your solution.
## The Jacobian-vector product (chain rule) takes the following form using summation sign: $\frac{\partial (cost)}{\partial (input)_i} = \sum_j \frac{\partial (output)_j}{\partial (input)_i} \frac{\partial (cost)}{\partial (output)_j}$
# Once again note that, in the `backward` method below, $i^{th}$ component of `input_grad` and $j^{th}$ component of `output_grad` are denoted by $\frac{\partial (cost)}{\partial (input)_i}$ and $\frac{\partial (cost)}{\partial (output)_j}$, respectively.

In [0]:
# Inherit from Function
class My_softmax(Function):

    # Note that both forward and backward are @staticmethods
    @staticmethod
    def forward(ctx, input):
        output = F.softmax(input,dim=0)
        ctx.save_for_backward(output) # this is the only tensor you will need to save for backward function
        return output

    # This function has only a single output, so it gets only one gradient
    @staticmethod
    def backward(ctx, output_grad):
        output = ctx.saved_tensors[0]
        #print('output is', output)
        # retrieve saved tensors and use them in derivative calculation
        # return Jacobian-vecor product
        input_grad = torch.sum((torch.diag(output) - torch.ger(output,output)) * output_grad, 1)  # Complete this line
        return input_grad

# Gradient Descent on your own Huber Loss and your own softmax

In [9]:
y = torch.zeros(10)
y[2] = 1.0
print(y)
x = Variable(torch.randn(y.shape),requires_grad=True)
print(x)

optimizer = torch.optim.SGD([x], lr=1e-1, momentum=0.9) # create an optimizer that will do gradient descent optimization

gradient_descent(x,optimizer,My_softmax.apply,My_Huber_Loss.apply,y,1000,100)


tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])
tensor([-0.9612, -0.8806,  0.8634,  0.4036, -1.0341, -1.2295,  0.7396,  0.8960,
        -0.4296,  0.0302], requires_grad=True)
Iteration: 0 Variable: [0.033 0.036 0.205 0.13  0.031 0.025 0.182 0.212 0.056 0.089] Loss: 0.370637
Iteration: 100 Variable: [0.003 0.004 0.949 0.008 0.003 0.003 0.009 0.009 0.005 0.007] Loss: 0.001482
Iteration: 200 Variable: [0.003 0.003 0.96  0.006 0.003 0.002 0.007 0.007 0.004 0.005] Loss: 0.000900
Iteration: 300 Variable: [0.002 0.002 0.966 0.005 0.002 0.002 0.006 0.006 0.003 0.005] Loss: 0.000647
Iteration: 400 Variable: [0.002 0.002 0.97  0.005 0.002 0.002 0.005 0.005 0.003 0.004] Loss: 0.000505
Iteration: 500 Variable: [0.002 0.002 0.973 0.004 0.002 0.001 0.005 0.005 0.003 0.004] Loss: 0.000414


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys


Iteration: 600 Variable: [0.002 0.002 0.975 0.004 0.002 0.001 0.004 0.004 0.003 0.003] Loss: 0.000350
Iteration: 700 Variable: [0.002 0.002 0.977 0.004 0.002 0.001 0.004 0.004 0.002 0.003] Loss: 0.000304
Iteration: 800 Variable: [0.002 0.002 0.978 0.003 0.001 0.001 0.004 0.004 0.002 0.003] Loss: 0.000268
Iteration: 900 Variable: [0.001 0.002 0.979 0.003 0.001 0.001 0.003 0.003 0.002 0.003] Loss: 0.000240
